In [9]:
import numpy as np

## Mixed NumPy Practice — Quiz Scores

This practice combines multiple NumPy concepts using a set of quiz scores.

### Concepts Practiced

- Creating a NumPy array
- Boolean indexing
- Modifying array values
- Sorting with `np.sort()`
- Aggregation: `sum()`, `mean()`, `max()`
- Median with `np.median()`
- Unique values with `np.unique()`
- Square root with `np.sqrt()`

In [10]:
# 1. CREATE THE ARRAY
scores = np.array([16, 25, 36, 25, 49, 64, 81, 100])

print("Original scores:")
print(scores)


# 2. UPDATE EVERY SCORE BELOW 25 TO 25
scores[scores < 25] = 25

print("\nUpdated scores:")
print(scores)


# 3. SORT THE UPDATED SCORES
sorted_scores = np.sort(scores)

print("\nSorted scores:")
print(sorted_scores)


# 4. FIND TOTAL, AVERAGE, HIGHEST VALUE AND MEDIAN
total = scores.sum()
average = scores.mean()
highest = scores.max()
median = np.median(scores)

print("\nStatistics -")
print("Total:", total)
print("Average:", average)
print("Highest:", highest)
print("Median:", median)


# 5. FIND DISTINCT SCORE VALUES
unique_scores = np.unique(scores)

print("\nUnique scores:")
print(unique_scores)


# 6. CALCULATE SQUARE ROOT OF EACH UPDATED SCORE
square_roots = np.sqrt(scores)

print("\nSquare roots:")
print(square_roots)

Original scores:
[ 16  25  36  25  49  64  81 100]

Updated scores:
[ 25  25  36  25  49  64  81 100]

Sorted scores:
[ 25  25  25  36  49  64  81 100]

Statistics -
Total: 405
Average: 50.625
Highest: 100
Median: 42.5

Unique scores:
[ 25  36  49  64  81 100]

Square roots:
[ 5.  5.  6.  5.  7.  8.  9. 10.]
