In [1]:
import numpy as np

# 1. Create a 2 × 4 NumPy array
scores = np.array([
    [35, 42, 50, 61],
    [28, 74, 81, 39]
])

print("Original scores:")
print(scores)


# 2. Add 5 grace marks to every score
# Broadcasting adds 5 to every element
updated_scores = scores + 5

print("\nUpdated scores:")
print(updated_scores)


# 3. Extract only the second row
second_row = updated_scores[1]

print("\nSecond row:")
print(second_row)


# 4. Filter values that are 50 or higher
filtered_scores = updated_scores[updated_scores >= 50]

print("\nScores 50 or higher:")
print(filtered_scores)


# 5. Use np.where()
# 50 or more → "Pass"
# Below 50 → "Needs Work"
result = np.where(
    updated_scores >= 50,
    "Pass",
    "Needs Work"
)

print("\nPass / Needs Work:")
print(result)

Original scores:
[[35 42 50 61]
 [28 74 81 39]]

Updated scores:
[[40 47 55 66]
 [33 79 86 44]]

Second row:
[33 79 86 44]

Scores 50 or higher:
[55 66 79 86]

Pass / Needs Work:
[['Needs Work' 'Needs Work' 'Pass' 'Pass']
 ['Needs Work' 'Pass' 'Pass' 'Needs Work']]


### Concepts practiced
- np.array() → array creation
- scores + 5 → broadcasting
- updated_scores[1] → row slicing/indexing
- updated_scores[updated_scores >= 50] → filtering / Boolean masking
- np.where() → conditional values