# Practice — Vectorization and Broadcasting

This practice combines two important NumPy concepts:

- **Vectorization** → performing operations on entire arrays without explicit Python loops.
- **Broadcasting** → applying a smaller array to a larger array when their shapes are compatible.

## 1. Vectorization

Create two NumPy arrays:

```python
a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

In [1]:
import numpy as np


# 1. VECTORIZATION

a = np.array([10, 20, 30, 40])
b = np.array([1, 2, 3, 4])

result = a * b

print("Array a:")
print(a)

print("\nArray b:")
print(b)

print("\nElement-wise multiplication:")
print(result)

print("\nShapes:")
print("a:", a.shape)
print("b:", b.shape)
print("result:", result.shape)


# 2. WHY IS THIS VECTORIZATION?

# Instead of using a Python loop like:
#
# result = []
# for i in range(len(a)):
#     result.append(a[i] * b[i])
#
# NumPy performs the operation on the entire arrays directly.

print("\nVectorization means:")
print("The operation is performed on the entire arrays without an explicit Python loop.")


# 3. BROADCASTING

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

bonus = np.array([10, 20, 30])

final_matrix = matrix + bonus

print("\nOriginal matrix:")
print(matrix)

print("\nBonus:")
print(bonus)

print("\nFinal matrix:")
print(final_matrix)


# 4. CHECK THE SHAPES

print("\nShapes:")
print("Matrix shape:", matrix.shape)
print("Bonus shape:", bonus.shape)
print("Result shape:", final_matrix.shape)


# 5. UNDERSTANDING BROADCASTING

# The bonus array has shape (3,).
#
# The matrix has shape (3, 3).
#
# NumPy broadcasts the bonus across every row:
#
# [10, 20, 30]
# [10, 20, 30]
# [10, 20, 30]
#
# Then element-wise addition is performed.

broadcast_bonus = np.broadcast_to(bonus, matrix.shape)

print("\nBonus after broadcasting:")
print(broadcast_bonus)


# 6. VERIFY THE BROADCASTING RESULT

expected_matrix = np.array([
    [11, 22, 33],
    [14, 25, 36],
    [17, 28, 39]
])

print("\nExpected matrix:")
print(expected_matrix)

print("\nIs the result correct?")
print(np.array_equal(final_matrix, expected_matrix))


# 7. FINAL ANSWERS

print("\nFinal Answer — Vectorization:")
print(result)

print("\nFinal Answer — Broadcasting:")
print(final_matrix)

print("\nBroadcasting direction:")
print("The bonus array is broadcast across the rows.")

Array a:
[10 20 30 40]

Array b:
[1 2 3 4]

Element-wise multiplication:
[ 10  40  90 160]

Shapes:
a: (4,)
b: (4,)
result: (4,)

Vectorization means:
The operation is performed on the entire arrays without an explicit Python loop.

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Bonus:
[10 20 30]

Final matrix:
[[11 22 33]
 [14 25 36]
 [17 28 39]]

Shapes:
Matrix shape: (3, 3)
Bonus shape: (3,)
Result shape: (3, 3)

Bonus after broadcasting:
[[10 20 30]
 [10 20 30]
 [10 20 30]]

Expected matrix:
[[11 22 33]
 [14 25 36]
 [17 28 39]]

Is the result correct?
True

Final Answer — Vectorization:
[ 10  40  90 160]

Final Answer — Broadcasting:
[[11 22 33]
 [14 25 36]
 [17 28 39]]

Broadcasting direction:
The bonus array is broadcast across the rows.
