### NumPy Array Operations & Manipulation

In [35]:
import numpy as np

##### 1D ARRAY INDEXING & SLICING

In [36]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])


# INDEXING
# Index starts from 0.
print("First element:", arr[0])

# Negative index starts from the end.
print("Last element:", arr[-1])


# SLICING
# arr[start:stop] → stop index is NOT included.
print("Basic slicing:", arr[2:7])

# start:stop:step
print("With step:", arr[1:7:2])

# Take elements from the beginning.
print("First 3 elements:", arr[:3])

# Take elements until the end.
print("From index 3:", arr[3:])

# Take elements from the end.
print("Last 3 elements:", arr[-3:])

# Reverse the array using a negative step.
print("Reversed array:", arr[::-1])

First element: 1
Last element: 7
Basic slicing: [3 4 5 6 7]
With step: [2 4 6]
First 3 elements: [1 2 3]
From index 3: [4 5 6 7]
Last 3 elements: [5 6 7]
Reversed array: [7 6 5 4 3 2 1]


### 2D ARRAY INDEXING

In [37]:
arr_2D = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])


# INDEXING
# arr[row, column]
print("Specific element:", arr_2D[1, 2])

# First row
print("First row:", arr_2D[0])

# Second row
print("Second row:", arr_2D[1])

# Last row
print("Last row:", arr_2D[-1])


# COLUMN
# : means take all rows.
print("First column:", arr_2D[:, 0])
print("Second column:", arr_2D[:, 1])
print("Last column:", arr_2D[:, -1])


# SLICING
# Take rows 0 and 1, and columns 1 and 2.
print("2D slice:")
print(arr_2D[0:2, 1:3])


# Take all rows, but only first two columns.
print("First two columns:")
print(arr_2D[:, 0:2])


# Take first two rows, but all columns.
print("First two rows:")
print(arr_2D[0:2, :])


# REVERSE
# Reverse both rows and columns.
print("Reversed 2D array:")
print(arr_2D[::-1, ::-1])

Specific element: 6
First row: [1 2 3]
Second row: [4 5 6]
Last row: [7 8 9]
First column: [1 4 7]
Second column: [2 5 8]
Last column: [3 6 9]
2D slice:
[[2 3]
 [5 6]]
First two columns:
[[1 2]
 [4 5]
 [7 8]]
First two rows:
[[1 2 3]
 [4 5 6]]
Reversed 2D array:
[[9 8 7]
 [6 5 4]
 [3 2 1]]


### Sorting

In [38]:
# SORTING
# np.sort() returns a sorted copy of the array.
arr = np.array([5, 2, 8, 1, 9, 3, -5,-1, 50, 2])

print("Original array:", arr)
print("Sorted array:", np.sort(arr))

# argsort() in descending order
descending_indices = np.argsort(arr)[::-1]

print("Descending indexes:", descending_indices)
print("Descending array:", arr[descending_indices])


# SORTING A 2D ARRAY
arr_2D = np.array([
    [5, 2, 8],
    [9, 1, 4]
])

# axis=1 → sort each row
print("\nSort each row: ")
print(np.sort(arr_2D, axis=1))

# axis=0 → sort each column
print("Sort each column:")
print(np.sort(arr_2D, axis=0))


# argsort() gives the indexes that will put the array in sorted order.
arr = np.array([40, 10, 30, 20])

print("Original:", arr)
print("Sorted indexes:", np.argsort(arr))
print("Sorted array:", arr[np.argsort(arr)])

Original array: [ 5  2  8  1  9  3 -5 -1 50  2]
Sorted array: [-5 -1  1  2  2  3  5  8  9 50]
Descending indexes: [8 4 2 0 5 9 1 3 7 6]
Descending array: [50  9  8  5  3  2  2  1 -1 -5]

Sort each row: 
[[2 5 8]
 [1 4 9]]
Sort each column:
[[5 1 4]
 [9 2 8]]
Original: [40 10 30 20]
Sorted indexes: [1 3 2 0]
Sorted array: [10 20 30 40]


### Filter

In [39]:
numbers = np.array([1,2,3,4,5,1,3,8,9,4,55,90])

even_numbers = numbers[numbers % 2 == 0]
print("even numbers: ", even_numbers)

# array[condition] → filter elements using a condition
print("Greater than 10:", numbers[numbers > 10])
print("Less than 5:", numbers[numbers < 5])
print("Equal to 4:", numbers[numbers == 4])
print("Even numbers:", numbers[numbers % 2 == 0])

# Filter with mask
mask = numbers > 5
print("Numbers greater than 5:", numbers[mask])

# Mask → tells us True / False
# numbers[mask] → keeps only True values
mask = numbers % 2 == 0
print("Mask:", mask)
print("Filtered:", numbers[mask])


# Filtering = array[condition]

even numbers:  [ 2  4  8  4 90]
Greater than 10: [55 90]
Less than 5: [1 2 3 4 1 3 4]
Equal to 4: [4 4]
Even numbers: [ 2  4  8  4 90]
Numbers greater than 5: [ 8  9 55 90]
Mask: [False  True False  True False False False  True False  True False  True]
Filtered: [ 2  4  8  4 90]


### fancy indexing vs np.where()

In [40]:
num = np.array([3, 6, 9, 1, 5, 0, 2, 4, 55, -1])


# FANCY INDEXING
# Give specific indexes and get those elements.
indices = [0, 2, 4]
print("Fancy indexing:", num[indices])


# NP.WHERE() — GET INDEXES
# np.where(condition)
# Returns the indexes where the condition is True.
where_result = np.where(num > 5)
print("Indexes:", where_result[0])
# Use the indexes to get the actual values.
print("Values:", num[where_result[0]])


# NP.WHERE() — CONDITION

# np.where(condition, value_if_true, value_if_false)

# If number > 5 → multiply by 4
# Otherwise     → keep the original number.

condition_array = np.where(
    num > 5,
    num * 4,
    num
)

print("Condition result:", condition_array)

Fancy indexing: [3 9 5]
Indexes: [1 2 8]
Values: [ 6  9 55]
Condition result: [  3  24  36   1   5   0   2   4 220  -1]


### adding and removing data

In [41]:
# merging of two array
arr1 = np.array([1,2,3,4])
arr2 = np.array([4,5,6,7])

combine_array = np.concatenate((arr1 , arr2))
print(combine_array)

# For 2D arrays
# Here axis becomes important:
arr1 = np.array([
    [1, 2],
    [3, 4]
])

arr2 = np.array([
    [5, 6],
    [7, 8]
])

# Add rows
print(np.concatenate((arr1, arr2), axis=0))

# Add columns
print(np.concatenate((arr1, arr2), axis=1))

[1 2 3 4 4 5 6 7]
[[1 2]
 [3 4]
 [5 6]
 [7 8]]
[[1 2 5 6]
 [3 4 7 8]]


##### compatibility shapes

In [42]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
c = np.array([7,8,9,10,3])

# Check whether two arrays have exactly the same shape.
print("compatibility shapes: ", a.shape == b.shape)
print("compatibility shapes: ", a.shape == c.shape)


compatibility shapes:  True
compatibility shapes:  False


##### ARRAY MANIPULATION

In [43]:
original = np.array([[1, 2], [3, 4]])
new_row = np.array([[5, 6]])

# Add a new row
with_new_row = np.vstack((original, new_row))

print(original)
print(with_new_row)


new_col = np.array([[7], [8]])

# Add a new column
with_new_col = np.hstack((original, new_col))

print("With new column:", with_new_col)

# vstack → add rows ↓
# hstack → add columns →

[[1 2]
 [3 4]]
[[1 2]
 [3 4]
 [5 6]]
With new column: [[1 2 7]
 [3 4 8]]


##### deleting element

In [44]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

# Delete element at index 3
deleted = np.delete(arr, 3)

print("Original:", arr)
print("After deleting:", deleted)

Original: [1 2 3 4 5 6 7]
After deleting: [1 2 3 5 6 7]


### Modifying Array Values

In [45]:
# MODIFYING ARRAY VALUES

# NumPy arrays are mutable.
# This means we can change existing values after creating the array.

scores = np.array([45, 67, 72, 59, 88, 34])

print("Original array:")
print(scores)


# 1. CHANGE ONE VALUE
# Indexing allows us to access and modify one specific element.
# Index 0 contains 45.
# We change it to 50.

scores[0] = 50

print("\nAfter changing index 0:")
print(scores)


# 2. CHANGE A VALUE USING NEGATIVE INDEX
# Negative indexing starts from the end.
# -1 means the last element.
# The last value is 34.
# We change it to 40.

scores[-1] = 40

print("\nAfter changing the last value:")
print(scores)


# 3. REPLACE A SLICE
# Slicing allows us to modify multiple neighboring elements.
# scores[1:3] means:
# index 1 and index 2
# Current values:
# index 1 -> 67
# index 2 -> 72
# We replace them with 70 and 75.

scores[1:3] = [70, 75]

print("\nAfter replacing a slice:")
print(scores)


# 4. MODIFY MULTIPLE VALUES USING A CONDITION
# Boolean masking can also be used to modify values.
# Find all values less than 40.
# Wherever the condition is True,
# replace that value with 40.

scores[scores < 40] = 40

print("\nAfter replacing scores below 40 with 40:")
print(scores)


# 5. MODIFY SELECTED POSITIONS
# We can provide multiple indexes inside a list.
# [3, 4] means:
# index 3
# index 4
# We replace those positions with 60 and 90.

scores[[3, 4]] = [60, 90]

print("\nAfter modifying selected indexes:")
print(scores)

Original array:
[45 67 72 59 88 34]

After changing index 0:
[50 67 72 59 88 34]

After changing the last value:
[50 67 72 59 88 40]

After replacing a slice:
[50 70 75 59 88 40]

After replacing scores below 40 with 40:
[50 70 75 59 88 40]

After modifying selected indexes:
[50 70 75 60 90 40]
