In [2]:
import numpy as np

### NumPy `np.where()` Function

The `np.where()` function is a powerful tool in NumPy.

It evaluates a condition **element-by-element** and returns one value when the condition is `True` and another value when the condition is `False`.

#### Syntax

```python
np.where(condition, value_if_true, value_if_false)

### Basic np.where()

In [3]:
# np.where() checks a condition element-by-element.
#
# Syntax:
# np.where(condition, value_if_true, value_if_false)

numbers = np.array([1, 2, 3, 4, 5, 6])

# If the number is even -> "Even"
# Otherwise -> "Odd"
result = np.where(numbers % 2 == 0, "Even", "Odd")

print(result)

['Odd' 'Even' 'Odd' 'Even' 'Odd' 'Even']


### Convert Grades

In [4]:
# If score >= 50 -> "Pass"
# Otherwise -> "Fail"

scores = np.array([45, 67, 32, 90, 58])

result = np.where(
    scores >= 50,
    "Pass",
    "Fail"
)

print(result)

['Fail' 'Pass' 'Fail' 'Pass' 'Pass']


### Replace Negative Numbers

In [5]:
# Replace negative numbers with 0.
# Keep positive numbers and 0 unchanged.

nums = np.array([-4, -1, 3, -7, 8, 0])

positive_nums = np.where(
    nums < 0,   # Condition
    0,          # Value if True
    nums        # Value if False
)

print(positive_nums)

[0 0 3 0 8 0]


### Apply Discount

In [6]:
# Apply a 10% discount if price > 100.
# Otherwise, keep the original price.

prices = np.array([80, 120, 150, 90, 200])

final_prices = np.where(
    prices > 100,
    prices * 0.9,   # 10% discount
    prices          # No discount
)

print(final_prices)

[ 80. 108. 135.  90. 180.]


### Categorize Ages

In [7]:
# If age < 18 -> "Child"
# Otherwise -> "Adult"

ages = np.array([8, 15, 22, 35, 60, 70])

category = np.where(
    ages < 18,
    "Child",
    "Adult"
)

print(category)

['Child' 'Child' 'Adult' 'Adult' 'Adult' 'Adult']


### Cap Values

In [8]:
# If value > 100 -> replace it with 100.
# Otherwise, keep the original value.

values = np.array([10, 25, 50, 75, 120])

capped = np.where(
    values > 100,
    100,
    values
)

print(capped)

[ 10  25  50  75 100]


## Practice Questions

### Student Pass/Fail

In [9]:
# Q1.
# A student passes if marks >= 40.
# Otherwise, the student fails.

marks = np.array([35, 45, 67, 28, 90, 39])

result = np.where(
    marks >= 40,
    "Pass",
    "Fail"
)

print(result)

['Fail' 'Pass' 'Pass' 'Fail' 'Pass' 'Fail']


### Absent Students

In [10]:
# Q2.
# Absent students are marked with -1.
# Replace -1 with 0.
# Keep all other marks unchanged.

marks = np.array([78, -1, 56, 89, -1, 45])

new_marks = np.where(
    marks < 0,
    0,
    marks
)

print(new_marks)

[78  0 56 89  0 45]


### Free Delivery

In [11]:
# Q3.
# Delivery charge is:
#   0  -> if order amount >= 499
#   40 -> otherwise
#
# Then calculate the total amount to pay.
# Total = order amount + delivery charge

orders = np.array([250, 499, 799, 120, 1500])

# Add delivery charge.
# If order >= 499 -> no delivery charge.
# Otherwise -> add 40.

bill = np.where(
    orders >= 499,
    orders,
    orders + 40
)

print("Final bill:", bill)

Final bill: [ 290  499  799  160 1500]


### Salary Hike

In [12]:
# Q4.
# Salary hike:
#   20% hike -> if salary < 30000
#   10% hike -> otherwise
#
# Find the new salary.

salaries = np.array([25000, 45000, 18000, 60000, 30000])

new_salaries = np.where(
    salaries < 30000,
    salaries * 1.20,   # 20% hike
    salaries * 1.10    # 10% hike
)

print("New salaries:", new_salaries)

New salaries: [30000. 49500. 21600. 66000. 33000.]


### Phone Battery Status

In [14]:
# Q5.
# We have two arrays:
#
# battery    -> battery percentage
# is_charging -> whether the phone is plugged in
#
# Rules:
# 1. If phone is plugged in -> "Charging"
# 2. If NOT plugged in AND battery < 20 -> "Charge Now"
# 3. Otherwise -> "OK"

battery = np.array([15, 80, 5, 45, 19, 10])

is_charging = np.array([
    False,
    False,
    True,
    False,
    False,
    True
])

# First check whether the phone is charging.
#
# If True:
#     "Charging"
#
# If False:
#     Check battery level using another np.where().
#
status = np.where(
    is_charging,
    "Charging",
    np.where(
        battery < 20,
        "Charge Now",
        "OK"
    )
)

print(status)

['Charge Now' 'OK' 'Charging' 'OK' 'Charge Now' 'Charging']


### Stock Report

In [15]:
# Q6.
# We have yesterday's and today's stock prices.
#
# First calculate percentage change:
#
# percentage change =
# (today - yesterday) / yesterday * 100
#
# Then classify the change:
#
# change > 5  -> "Big Jump"
# change > 0  -> "Up"
# change < 0  -> "Down"
# otherwise   -> "No Change"

yesterday = np.array([200, 150, 320, 90, 500, 75])

today = np.array([215, 150, 310, 93, 500, 72])

# Calculate percentage change for every stock.
change = (today - yesterday) / yesterday * 100

print("Percentage change:")
print(change)

# Nested np.where():
#
# First:
# change > 5 -> "Big Jump"
#
# Otherwise:
#     change > 0 -> "Up"
#
#     Otherwise:
#         change < 0 -> "Down"
#
#         Otherwise:
#             "No Change"

label = np.where(
    change > 5,
    "Big Jump",
    np.where(
        change > 0,
        "Up",
        np.where(
            change < 0,
            "Down",
            "No Change"
        )
    )
)

print("\nStock status:")
print(label)

Percentage change:
[ 7.5         0.         -3.125       3.33333333  0.         -4.        ]

Stock status:
['Big Jump' 'No Change' 'Down' 'Up' 'No Change' 'Down']


### modifying an array with np.where()

In [16]:
# np.where() does not modify the original array.
# It creates and returns a new array.

numbers = np.array([10, 20, 30, 40, 50])

new_numbers = np.where(
    numbers >= 30,
    numbers * 2,
    numbers
)

print("Original:", numbers)
print("New:", new_numbers)

Original: [10 20 30 40 50]
New: [ 10  20  60  80 100]
