In [2]:
import numpy as np

### Filtering array practice

#### Filtering Arrays

Filtering means selecting only the elements from a NumPy array
that satisfy a given condition.

NumPy uses a Boolean condition to decide which elements to keep.

```python
array[condition]

The condition produces a Boolean mask:
True  → keep the element
False → ignore the element

Key Points
- Filtering selects elements based on a condition.
- Conditions produce Boolean masks.
- True values are kept.
- False values are ignored.
- & is used for AND.
- | is used for OR.
- Use parentheses around each condition.
- Boolean masking is one of the most important NumPy concepts
  for data analysis and machine learning.

In [3]:
# FILTERING ARRAYS
ages = np.array([
    4, 9, 13, 17,
    18, 22, 29, 35,
    7, 15, 41, 63
])

print("Original ages:")
print(ages)


# 1. BOOLEAN MASK
# Check which ages are 18 or above.
adult_mask = ages >= 18
print("\nAdult mask:")
print(adult_mask)


# 2. FILTER USING MASK
# Keep only the values where the mask is True.
adults = ages[adult_mask]
print("\nAdults:")
print(adults)


# 3. FILTER DIRECTLY
# We can also put the condition directly
# inside the array.
print("\nAdults using direct filtering:")
print(ages[ages >= 18])


# 4. ONLY CHILDREN
# Keep ages below 18.
child_mask = ages < 18
print("\nChild mask:")
print(child_mask)

children = ages[child_mask]
print("Children:")
print(children)


# 5. ONLY TEENS
# Keep ages from 15 to 18.

teen_mask = (ages >= 15) & (ages <= 18)
print("\nTeen mask:")
print(teen_mask)

teens = ages[teen_mask]
print("Teens:")
print(teens)


# 6. WORKING-AGE ADULTS
# Keep ages from 18 to 60.

working_mask = (ages >= 18) & (ages <= 60)
print("\nWorking-age mask:")
print(working_mask)

working_adults = ages[working_mask]
print("Working-age adults:")
print(working_adults)


# 7. VERY YOUNG OR SENIOR
# Keep ages below 10 OR above 60.

special_mask = (ages < 10) | (ages > 60)
print("\nSpecial mask:")
print(special_mask)

special_ages = ages[special_mask]

print("Very young or senior:")
print(special_ages)


# 8. GREATER THAN
print("\nAges greater than 20:")
print(ages[ages > 20])


# 9. GREATER THAN OR EQUAL TO
print("\nAges greater than or equal to 30:")
print(ages[ages >= 30])


# 10. LESS THAN
print("\nAges less than 20:")
print(ages[ages < 20])


# 11. LESS THAN OR EQUAL TO
print("\nAges less than or equal to 20:")
print(ages[ages <= 20])


# 12. EQUAL TO
print("\nAges equal to 18:")
print(ages[ages == 18])


# 13. NOT EQUAL TO
print("\nAges not equal to 18:")
print(ages[ages != 18])


# 14. BETWEEN TWO VALUES
# Keep values from 20 to 40.
between_mask = (ages >= 20) & (ages <= 40)
print("\nAges between 20 and 40:")
print(ages[between_mask])


# 15. OUTSIDE A RANGE
# Keep values below 20 OR above 40.
outside_mask = (ages < 20) | (ages > 40)
print("\nAges outside 20 to 40:")
print(ages[outside_mask])

Original ages:
[ 4  9 13 17 18 22 29 35  7 15 41 63]

Adult mask:
[False False False False  True  True  True  True False False  True  True]

Adults:
[18 22 29 35 41 63]

Adults using direct filtering:
[18 22 29 35 41 63]

Child mask:
[ True  True  True  True False False False False  True  True False False]
Children:
[ 4  9 13 17  7 15]

Teen mask:
[False False False  True  True False False False False  True False False]
Teens:
[17 18 15]

Working-age mask:
[False False False False  True  True  True  True False False  True False]
Working-age adults:
[18 22 29 35 41]

Special mask:
[ True  True False False False False False False  True False False  True]
Very young or senior:
[ 4  9  7 63]

Ages greater than 20:
[22 29 35 41 63]

Ages greater than or equal to 30:
[35 41 63]

Ages less than 20:
[ 4  9 13 17 18  7 15]

Ages less than or equal to 20:
[ 4  9 13 17 18  7 15]

Ages equal to 18:
[18]

Ages not equal to 18:
[ 4  9 13 17 22 29 35  7 15 41 63]

Ages between 20 and 40:
[22 29 35]



In [4]:
# 1. Define the two arrays

names = np.array([
    "Aarav",
    "Diya",
    "Rohan",
    "Sneha",
    "Kabir",
    "Meera",
    "Ishaan",
    "Pooja"
])

ages = np.array([16, 22, 35, 12, 27, 41, 19, 8])


# 2. Create a Boolean mask from the ages array
# Select ages between 18 and 40

age_mask = (ages >= 18) & (ages <= 40)

print("Age mask:")
print(age_mask)


# 3. Use the same mask to filter both arrays

filtered_names = names[age_mask]
filtered_ages = ages[age_mask]

print("\nFiltered names:")
print(filtered_names)

print("\nFiltered ages:")
print(filtered_ages)

Age mask:
[False  True  True False  True False  True False]

Filtered names:
['Diya' 'Rohan' 'Kabir' 'Ishaan']

Filtered ages:
[22 35 27 19]
