In [2]:
import numpy as np

### Indexing and Slicing practice

In [3]:
# Create the array - 1D array
city_array = np.array([
    "Mumbai",
    "Delhi",
    "Bengaluru",
    "Hyderabad",
    "Chennai",
    "Pune",
    "Jaipur",
    "Ahmedabad",
    "Kolkata",
    "Lucknow"
])
print(city_array)

# POSITIVE & NEGATIVE INDEXING
print(f"city_array[0] = {city_array[0]}")
print(f"city_array[1] = {city_array[1]}")
print(f"city_array[4] = {city_array[4]}")

print(f"city_array[-1] = {city_array[-1]}")
print(f"city_array[-2] = {city_array[-2]}")
print(f"city_array[-5] = {city_array[-5]}")


# BASIC SLICING
print(f"city_array[5:9] = {city_array[5:9]}")
print(f"city_array[2:6] = {city_array[2:6]}")
print(f"city_array[0:4] = {city_array[0:4]}")


# SLICING FROM START
print(f"city_array[:5] = {city_array[:5]}")
print(f"city_array[:3] = {city_array[:3]}")


# SLICING UNTIL END
print(f"city_array[5:] = {city_array[5:]}")
print(f"city_array[7:] = {city_array[7:]}")


# SLICING WITH STEP
print(f"city_array[1::2] = {city_array[1::2]}")
print(f"city_array[0::2] = {city_array[0::2]}")


# REVERSE ARRAY
print(f"city_array[::-1] = {city_array[::-1]}")


# REVERSE PART OF ARRAY
print(f"city_array[7:2:-1] = {city_array[7:2:-1]}")

['Mumbai' 'Delhi' 'Bengaluru' 'Hyderabad' 'Chennai' 'Pune' 'Jaipur'
 'Ahmedabad' 'Kolkata' 'Lucknow']
city_array[0] = Mumbai
city_array[1] = Delhi
city_array[4] = Chennai
city_array[-1] = Lucknow
city_array[-2] = Kolkata
city_array[-5] = Pune
city_array[5:9] = ['Pune' 'Jaipur' 'Ahmedabad' 'Kolkata']
city_array[2:6] = ['Bengaluru' 'Hyderabad' 'Chennai' 'Pune']
city_array[0:4] = ['Mumbai' 'Delhi' 'Bengaluru' 'Hyderabad']
city_array[:5] = ['Mumbai' 'Delhi' 'Bengaluru' 'Hyderabad' 'Chennai']
city_array[:3] = ['Mumbai' 'Delhi' 'Bengaluru']
city_array[5:] = ['Pune' 'Jaipur' 'Ahmedabad' 'Kolkata' 'Lucknow']
city_array[7:] = ['Ahmedabad' 'Kolkata' 'Lucknow']
city_array[1::2] = ['Delhi' 'Hyderabad' 'Pune' 'Ahmedabad' 'Lucknow']
city_array[0::2] = ['Mumbai' 'Bengaluru' 'Chennai' 'Jaipur' 'Kolkata']
city_array[::-1] = ['Lucknow' 'Kolkata' 'Ahmedabad' 'Jaipur' 'Pune' 'Chennai' 'Hyderabad'
 'Bengaluru' 'Delhi' 'Mumbai']
city_array[7:2:-1] = ['Ahmedabad' 'Jaipur' 'Pune' 'Chennai' 'Hyderabad']


In [4]:
# Create the array - 2D array
arr_2D = np.array([
    [10, 20, 30, 40],
    [50, 60, 70, 80],
    [90, 100, 110, 120]
])

print(arr_2D)

# SPECIFIC ELEMENT
print(f"arr_2D[0, 0] = {arr_2D[0, 0]}")
print(f"arr_2D[1, 2] = {arr_2D[1, 2]}")
print(f"arr_2D[2, 3] = {arr_2D[2, 3]}")


# ROWS
print(f"arr_2D[0] = {arr_2D[0]}")
print(f"arr_2D[1] = {arr_2D[1]}")
print(f"arr_2D[-1] = {arr_2D[-1]}")


# COLUMNS
print(f"arr_2D[:, 0] = {arr_2D[:, 0]}")
print(f"arr_2D[:, 1] = {arr_2D[:, 1]}")
print(f"arr_2D[:, -1] = {arr_2D[:, -1]}")


# 2D SLICING
print(f"arr_2D[0:2, 1:3] =\n{arr_2D[0:2, 1:3]}")

print(f"arr_2D[:, 0:2] =\n{arr_2D[:, 0:2]}")

print(f"arr_2D[1:, :] =\n{arr_2D[1:, :]}")

print(f"arr_2D[:2, :] =\n{arr_2D[:2, :]}")


# REVERSE ROWS
print(f"arr_2D[::-1, :] =\n{arr_2D[::-1, :]}")

# REVERSE COLUMNS
print(f"arr_2D[:, ::-1] =\n{arr_2D[:, ::-1]}")

# REVERSE BOTH
print(f"arr_2D[::-1, ::-1] =\n{arr_2D[::-1, ::-1]}")

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]
arr_2D[0, 0] = 10
arr_2D[1, 2] = 70
arr_2D[2, 3] = 120
arr_2D[0] = [10 20 30 40]
arr_2D[1] = [50 60 70 80]
arr_2D[-1] = [ 90 100 110 120]
arr_2D[:, 0] = [10 50 90]
arr_2D[:, 1] = [ 20  60 100]
arr_2D[:, -1] = [ 40  80 120]
arr_2D[0:2, 1:3] =
[[20 30]
 [60 70]]
arr_2D[:, 0:2] =
[[ 10  20]
 [ 50  60]
 [ 90 100]]
arr_2D[1:, :] =
[[ 50  60  70  80]
 [ 90 100 110 120]]
arr_2D[:2, :] =
[[10 20 30 40]
 [50 60 70 80]]
arr_2D[::-1, :] =
[[ 90 100 110 120]
 [ 50  60  70  80]
 [ 10  20  30  40]]
arr_2D[:, ::-1] =
[[ 40  30  20  10]
 [ 80  70  60  50]
 [120 110 100  90]]
arr_2D[::-1, ::-1] =
[[120 110 100  90]
 [ 80  70  60  50]
 [ 40  30  20  10]]
