In [23]:
import numpy as np

# NumPy Array Aggregation Methods

Array aggregation means summarizing multiple values into a smaller number of values.

Common aggregation methods:

- `sum()` → total
- `mean()` → average
- `min()` → minimum
- `max()` → maximum
- `std()` → standard deviation
- `var()` → variance
- `median()` → middle value
- `percentile()` → value at or below which a given percentage of data falls
- `quantile()` → percentile expressed as a value between 0 and 1

For 1D arrays, aggregation usually produces a single value.

For 2D arrays, we can use the `axis` parameter to control the direction of aggregation.

### Understanding `axis`

Consider a 2D array:

```text
             Q1   Q2   Q3   Q4
Store A     120  150  180  200
Store B     100  170  160  210
Store C     140  130  190  220

In [24]:
sales = np.array([
    [120, 150, 180, 200],
    [100, 170, 160, 210],
    [140, 130, 190, 220]
])

print("Sales:\n", sales)

print("\nWhole array total:")
print(sales.sum())

print("\nColumn-wise sum (axis=0):")
print(sales.sum(axis=0))

print("\nRow-wise sum (axis=1):")
print(sales.sum(axis=1))

Sales:
 [[120 150 180 200]
 [100 170 160 210]
 [140 130 190 220]]

Whole array total:
1970

Column-wise sum (axis=0):
[360 450 530 630]

Row-wise sum (axis=1):
[650 640 680]


In [25]:
# Basic Aggregation
print("Whole array sum:", sales.sum())
print("Whole array mean:", sales.mean())
print("Whole array min:", sales.min())
print("Whole array max:", sales.max())
print("Whole array std:", sales.std())
print("Whole array variance:", sales.var())

# Column-wise Aggregation
print("\nColumn-wise:")
print("Sum :", sales.sum(axis=0))
print("Mean:", sales.mean(axis=0))
print("Min :", sales.min(axis=0))
print("Max :", sales.max(axis=0))

# Row-wise Aggregation
print("\nRow-wise:")
print("Sum :", sales.sum(axis=1))
print("Mean:", sales.mean(axis=1))
print("Min :", sales.min(axis=1))
print("Max :", sales.max(axis=1))

Whole array sum: 1970
Whole array mean: 164.16666666666666
Whole array min: 100
Whole array max: 220
Whole array std: 35.93010189551683
Whole array variance: 1290.972222222222

Column-wise:
Sum : [360 450 530 630]
Mean: [120.         150.         176.66666667 210.        ]
Min : [100 130 160 200]
Max : [140 170 190 220]

Row-wise:
Sum : [650 640 680]
Mean: [162.5 160.  170. ]
Min : [120 100 130]
Max : [200 210 220]


## Median, Percentiles and Quantiles

Median and percentiles are statistical functions used to understand the
center and distribution of data.

They are especially useful when data contains outliers because the median
is less sensitive to extreme values than the mean.

### Median

`np.median()` returns the middle value after sorting the data.

- If the number of values is odd → the middle value is returned.
- If the number of values is even → the average of the two middle values is returned.

```python
np.median(array)

In [26]:
# Example 1D sales data for statistical analysis
sales_data = np.array([120, 150, 180, 200, 210, 220, 260])

# Median
median = np.median(sales_data)

# 25th, 50th and 75th percentiles
percentiles = np.percentile(sales_data, [25, 50, 75])

# Equivalent quantiles
quantiles = np.quantile(sales_data, [0.25, 0.50, 0.75])

# 90th percentile
percentile_90 = np.percentile(sales_data, 90)

print("Median:", median)
print("Percentiles [25, 50, 75]:", percentiles)
print("Quantiles [0.25, 0.50, 0.75]:", quantiles)
print("90th Percentile:", percentile_90)

Median: 200.0
Percentiles [25, 50, 75]: [165. 200. 215.]
Quantiles [0.25, 0.50, 0.75]: [165. 200. 215.]
90th Percentile: 236.0


### Practical Example — Sales Analysis

We can use aggregation methods to answer business questions:

- What are the total sales?
- What is the average sales?
- Which store has the highest total sales?
- Which quarter performed best overall?
- What is the highest sale made by each store?

In [27]:
# Total sales across all stores and quarters
total_sales = sales.sum()

# Average sales across all values
average_sales = sales.mean()

# Median of all sales values
median_sales = np.median(sales)

# 75th percentile of all sales values
percentile_75 = np.percentile(sales, 75)

# Total sales for each store
store_totals = sales.sum(axis=1)

# Total sales for each quarter
quarter_totals = sales.sum(axis=0)

# Highest sale for each store
highest_per_store = sales.max(axis=1)

# Lowest sale for each store
lowest_per_store = sales.min(axis=1)

print("Total Sales:", total_sales)
print("Average Sales:", average_sales)
print("Median Sales:", median_sales)
print("75th Percentile:", percentile_75)

print("Store Totals:", store_totals)
print("Quarter Totals:", quarter_totals)

print("Highest Sale per Store:", highest_per_store)
print("Lowest Sale per Store:", lowest_per_store)

Total Sales: 1970
Average Sales: 164.16666666666666
Median Sales: 165.0
75th Percentile: 192.5
Store Totals: [650 640 680]
Quarter Totals: [360 450 530 630]
Highest Sale per Store: [200 210 220]
Lowest Sale per Store: [120 100 130]
