In [3]:
import numpy as np
import time


# NumPy Vectorization

Vectorization is one of the most important concepts in NumPy.

It means performing an operation on an entire NumPy array at once instead of explicitly processing elements one by one using Python loops.

Instead of telling Python:

> Take the first element, process it.  
> Take the second element, process it.  
> Take the third element, process it.  
> ...

We tell NumPy:

> Perform this operation on the entire array.

NumPy can then perform many numerical operations using optimized low-level code.

---

## 1. What is Vectorization?

Vectorization means replacing explicit Python loops with operations that work on entire NumPy arrays.

### Without Vectorization

Suppose we want to multiply every number by 2.

```python
numbers = [1, 2, 3, 4, 5]

result = []

for number in numbers:
    result.append(number * 2)

print(result)

In [4]:
# 1. BASIC VECTORIZATION

numbers = np.array([1, 2, 3, 4, 5])

result = numbers * 2

print("Original array:")
print(numbers)

print("\nAfter multiplying by 2:")
print(result)


# 2. VECTOR OPERATIONS

a = np.array([1, 2, 3, 4])
b = np.array([10, 20, 30, 40])

print("\nVector addition:")
print(a + b)

print("\nVector subtraction:")
print(a - b)

print("\nElement-wise multiplication:")
print(a * b)

print("\nElement-wise division:")
print(a / b)


# 3. VECTOR OPERATIONS WITH SCALARS

scores = np.array([50, 60, 70, 80])

print("\nOriginal scores:")
print(scores)

print("\nAdd 5:")
print(scores + 5)

print("\nSubtract 5:")
print(scores - 5)

print("\nMultiply by 2:")
print(scores * 2)

print("\nDivide by 10:")
print(scores / 10)


# 4. VECTORIZATION WITH NUMPY FUNCTIONS

values = np.array([1, 4, 9, 16, 25])

print("\nSquare root:")
print(np.sqrt(values))

print("\nSquare:")
print(np.power(values, 2))

print("\nAbsolute values:")
negative_values = np.array([-10, -5, 0, 5, 10])
print(np.abs(negative_values))


# 5. VECTORIZE A MATHEMATICAL FORMULA

x = np.array([1, 2, 3, 4, 5])

# y = x² + 2x + 1
y = x**2 + 2*x + 1

print("\nValues of x:")
print(x)

print("\nResult of y = x² + 2x + 1:")
print(y)


# 6. VECTORIZATION WITH CONDITIONS

scores = np.array([35, 45, 55, 65, 75, 85])

passed_mask = scores >= 50

print("\nScores:")
print(scores)

print("\nPass/Fail mask:")
print(passed_mask)

print("\nPassed scores:")
print(scores[passed_mask])


# 7. VECTORIZE USING np.where()

result = np.where(scores >= 50, "Pass", "Fail")

print("\nPass/Fail result:")
print(result)


# 8. VECTORIZATION WITH A 2D ARRAY

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

result = matrix * 2

print("\nOriginal matrix:")
print(matrix)

print("\nMatrix multiplied by 2:")
print(result)


# 9. VECTORIZATION VS PYTHON LOOP

numbers = np.arange(1_000_000)


# Python loop
start = time.perf_counter()

loop_result = []

for number in numbers:
    loop_result.append(number * 2)

loop_time = time.perf_counter() - start


# NumPy vectorization
start = time.perf_counter()

numpy_result = numbers * 2

numpy_time = time.perf_counter() - start


print("\nPerformance comparison:")
print("Python loop time:", loop_time)
print("NumPy vectorized time:", numpy_time)


if numpy_time > 0:
    print("Speedup:", loop_time / numpy_time, "x")


# 10. VERIFY BOTH RESULTS

print("\nResults are equal:")
print(np.array_equal(np.array(loop_result), numpy_result))


# 11. VECTORIZATION + BROADCASTING

scores = np.array([50, 60, 70, 80])

bonus = 5

final_scores = scores + bonus

print("\nOriginal scores:")
print(scores)

print("\nBonus:")
print(bonus)

print("\nFinal scores:")
print(final_scores)


# 12. ML-STYLE EXAMPLE

X = np.array([
    [10, 100],
    [20, 200],
    [30, 300],
    [40, 400]
])

# Feature-wise mean
mean = X.mean(axis=0)

# Feature-wise standard deviation
std = X.std(axis=0)

# Vectorized standardization
X_scaled = (X - mean) / std

print("\nOriginal dataset:")
print(X)

print("\nFeature means:")
print(mean)

print("\nFeature standard deviations:")
print(std)

print("\nStandardized dataset:")
print(X_scaled)

Original array:
[1 2 3 4 5]

After multiplying by 2:
[ 2  4  6  8 10]

Vector addition:
[11 22 33 44]

Vector subtraction:
[ -9 -18 -27 -36]

Element-wise multiplication:
[ 10  40  90 160]

Element-wise division:
[0.1 0.1 0.1 0.1]

Original scores:
[50 60 70 80]

Add 5:
[55 65 75 85]

Subtract 5:
[45 55 65 75]

Multiply by 2:
[100 120 140 160]

Divide by 10:
[5. 6. 7. 8.]

Square root:
[1. 2. 3. 4. 5.]

Square:
[  1  16  81 256 625]

Absolute values:
[10  5  0  5 10]

Values of x:
[1 2 3 4 5]

Result of y = x² + 2x + 1:
[ 4  9 16 25 36]

Scores:
[35 45 55 65 75 85]

Pass/Fail mask:
[False False  True  True  True  True]

Passed scores:
[55 65 75 85]

Pass/Fail result:
['Fail' 'Fail' 'Pass' 'Pass' 'Pass' 'Pass']

Original matrix:
[[1 2 3]
 [4 5 6]]

Matrix multiplied by 2:
[[ 2  4  6]
 [ 8 10 12]]

Performance comparison:
Python loop time: 0.08697212500555906
NumPy vectorized time: 0.0010592499893391505
Speedup: 82.10727012593091 x

Results are equal:
True

Original scores:
[50 60 70 80]