# NumPy Broadcasting

Broadcasting is one of the most important concepts in NumPy.

It allows NumPy to perform operations between arrays with different shapes.

Instead of manually changing the smaller array to match the larger array, NumPy automatically applies the smaller array across the larger array when their shapes are compatible.

---

## 1. What is Broadcasting?

Broadcasting is NumPy's mechanism for performing element-wise operations between arrays of different shapes.

For example:

```python
import numpy as np

arr = np.array([1, 2, 3])

result = arr + 5

In [2]:
import numpy as np


# 1. BASIC SCALAR BROADCASTING

arr = np.array([1, 2, 3])

result = arr + 5

print("Original array:")
print(arr)

print("\nArray + scalar:")
print(result)


# Broadcasting also works with other operations.

print("\nSubtract 5:")
print(arr - 5)

print("\nMultiply by 5:")
print(arr * 5)

print("\nDivide by 5:")
print(arr / 5)


# 2. BROADCASTING WITH A 2D ARRAY

matrix = np.array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]
])

result = matrix + 1

print("\nOriginal matrix:")
print(matrix)

print("\nMatrix + 1:")
print(result)


# 3. ROW VECTOR BROADCASTING

matrix = np.array([
    [1, 2, 3],
    [1, 2, 3],
    [1, 2, 3]
])

row_vector = np.array([10, 20, 30])

result = matrix + row_vector

print("\nMatrix:")
print(matrix)

print("\nRow vector:")
print(row_vector)

print("\nMatrix + row vector:")
print(result)

print("\nShapes:")
print("Matrix shape:", matrix.shape)
print("Row vector shape:", row_vector.shape)


# 4. COLUMN VECTOR BROADCASTING

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

column_vector = np.array([
    [10],
    [20],
    [30]
])

result = matrix + column_vector

print("\nMatrix:")
print(matrix)

print("\nColumn vector:")
print(column_vector)

print("\nMatrix + column vector:")
print(result)

print("\nShapes:")
print("Matrix shape:", matrix.shape)
print("Column vector shape:", column_vector.shape)


# 5. CREATING A COLUMN VECTOR USING RESHAPE

values = np.array([10, 20, 30])

print("\nOriginal values:")
print(values)

print("Original shape:")
print(values.shape)

column_vector = values.reshape(3, 1)

print("\nAfter reshape:")
print(column_vector)

print("New shape:")
print(column_vector.shape)


# 6. ROW VECTOR VS COLUMN VECTOR

matrix = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

row = np.array([10, 20, 30])

column = np.array([10, 20, 30]).reshape(3, 1)

print("\nOriginal matrix:")
print(matrix)

print("\nAdd row vector:")
print(matrix + row)

print("\nAdd column vector:")
print(matrix + column)


# 7. BROADCASTING WITH DIFFERENT OPERATIONS

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60]
])

values = np.array([1, 2, 3])

print("\nAddition:")
print(matrix + values)

print("\nSubtraction:")
print(matrix - values)

print("\nMultiplication:")
print(matrix * values)

print("\nDivision:")
print(matrix / values)


# 8. COMPATIBLE SHAPES

A = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

B = np.array([10, 20, 30])

print("\nShape A:", A.shape)
print("Shape B:", B.shape)

print("\nA + B:")
print(A + B)

print("\nBroadcasted result shape:")
print(np.broadcast_shapes(A.shape, B.shape))


# 9. COMPATIBLE SHAPE: (3, 3) AND (3, 1)

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([
    [10],
    [20],
    [30]
])

print("\nShape A:", A.shape)
print("Shape B:", B.shape)

print("\nA + B:")
print(A + B)

print("\nResult shape:")
print(np.broadcast_shapes(A.shape, B.shape))


# 10. INCOMPATIBLE SHAPES

A = np.array([
    [1, 2, 3],
    [4, 5, 6],
    [7, 8, 9]
])

B = np.array([10, 20])

print("\nShape A:", A.shape)
print("Shape B:", B.shape)

try:
    result = A + B
    print(result)

except ValueError as error:
    print("\nBroadcasting failed.")
    print("Error:", error)


# 11. CHECK BROADCASTING COMPATIBILITY

shape_a = (3, 3)
shape_b = (3,)

print("\nShape A:", shape_a)
print("Shape B:", shape_b)

try:
    result_shape = np.broadcast_shapes(shape_a, shape_b)
    print("Broadcasting is possible.")
    print("Result shape:", result_shape)

except ValueError:
    print("Broadcasting is not possible.")


# 12. ANOTHER COMPATIBILITY TEST

shape_a = (3, 3)
shape_b = (2,)

print("\nShape A:", shape_a)
print("Shape B:", shape_b)

try:
    result_shape = np.broadcast_shapes(shape_a, shape_b)
    print("Broadcasting is possible.")
    print("Result shape:", result_shape)

except ValueError:
    print("Broadcasting is not possible.")


# 13. REAL-WORLD EXAMPLE — STUDENT BONUS

scores = np.array([
    [70, 80, 90],
    [60, 75, 85],
    [88, 92, 95]
])

bonus = np.array([5, 3, 2])

final_scores = scores + bonus

print("\nStudent scores:")
print(scores)

print("\nSubject-wise bonus:")
print(bonus)

print("\nFinal scores:")
print(final_scores)


# 14. REAL-WORLD EXAMPLE — SALES ADJUSTMENT

sales = np.array([
    [100, 200, 300],
    [150, 250, 350],
    [120, 220, 320]
])

adjustment = np.array([10, 20, 30])

adjusted_sales = sales + adjustment

print("\nOriginal sales:")
print(sales)

print("\nAdjustment:")
print(adjustment)

print("\nAdjusted sales:")
print(adjusted_sales)


# 15. MACHINE LEARNING STYLE EXAMPLE

X = np.array([
    [10, 100],
    [20, 200],
    [30, 300],
    [40, 400]
])

mean = X.mean(axis=0)
std = X.std(axis=0)

X_scaled = (X - mean) / std

print("\nOriginal dataset:")
print(X)

print("\nFeature means:")
print(mean)

print("\nFeature standard deviations:")
print(std)

print("\nStandardized dataset:")
print(X_scaled)


# 16. BROADCASTING WITH NUMPY FUNCTIONS

values = np.array([
    [1, 4, 9],
    [16, 25, 36]
])

addition = values + np.array([1, 2, 3])

square_root = np.sqrt(values)

power = np.power(values, 2)

print("\nOriginal values:")
print(values)

print("\nValues + [1, 2, 3]:")
print(addition)

print("\nSquare root:")
print(square_root)

print("\nPower of 2:")
print(power)


# 17. BROADCASTING VS EXPLICIT REPETITION

vector = np.array([1, 2, 3])

matrix = np.array([
    [10, 20, 30],
    [40, 50, 60],
    [70, 80, 90]
])

# Broadcasting
broadcast_result = matrix + vector

# Explicit repetition
repeated_vector = np.tile(vector, (3, 1))
tile_result = matrix + repeated_vector

print("\nBroadcasting result:")
print(broadcast_result)

print("\nRepeated vector:")
print(repeated_vector)

print("\nResult using explicit repetition:")
print(tile_result)

print("\nBoth results are equal:")
print(np.array_equal(broadcast_result, tile_result))


# 18. BROADCASTING SHAPE CHECK

examples = [
    ((3, 3), (3,)),
    ((3, 3), (3, 1)),
    ((2, 3), (3,)),
    ((4, 3), (4, 1)),
    ((3, 3), (2,))
]

print("\nBroadcasting compatibility examples:")

for shape_a, shape_b in examples:

    try:
        result_shape = np.broadcast_shapes(shape_a, shape_b)

        print(
            f"{shape_a} + {shape_b}"
            f" -> Compatible"
            f" -> Result shape: {result_shape}"
        )

    except ValueError:

        print(
            f"{shape_a} + {shape_b}"
            f" -> Not compatible"
        )

Original array:
[1 2 3]

Array + scalar:
[6 7 8]

Subtract 5:
[-4 -3 -2]

Multiply by 5:
[ 5 10 15]

Divide by 5:
[0.2 0.4 0.6]

Original matrix:
[[1 2 3]
 [1 2 3]
 [1 2 3]]

Matrix + 1:
[[2 3 4]
 [2 3 4]
 [2 3 4]]

Matrix:
[[1 2 3]
 [1 2 3]
 [1 2 3]]

Row vector:
[10 20 30]

Matrix + row vector:
[[11 22 33]
 [11 22 33]
 [11 22 33]]

Shapes:
Matrix shape: (3, 3)
Row vector shape: (3,)

Matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Column vector:
[[10]
 [20]
 [30]]

Matrix + column vector:
[[11 12 13]
 [24 25 26]
 [37 38 39]]

Shapes:
Matrix shape: (3, 3)
Column vector shape: (3, 1)

Original values:
[10 20 30]
Original shape:
(3,)

After reshape:
[[10]
 [20]
 [30]]
New shape:
(3, 1)

Original matrix:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Add row vector:
[[11 22 33]
 [14 25 36]
 [17 28 39]]

Add column vector:
[[11 12 13]
 [24 25 26]
 [37 38 39]]

Addition:
[[11 22 33]
 [41 52 63]]

Subtraction:
[[ 9 18 27]
 [39 48 57]]

Multiplication:
[[ 10  40  90]
 [ 40 100 180]]

Division:
[[10. 10. 10.]
 [40. 25. 2